# Generated by Django 5.1.5 on 2025-01-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_profile_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
